### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [jcrides/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by jcrides** [comment]
Thanks Marco. Should be all set now. Here's the commit https://github.com/jcrides/splurty/commit/3d2a9a5c1c6bc337996e870e94576baa78565f68
and has been deployed to heroku.

**Comment by MarcoMorawec** [comment]
@jcrides :+1: 

Nice work. Make sure you close the issue now that you're app looks all good on mobile :)
